version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - yarn install --lock-file

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://${DEPLOY_BUCKET}
